# Web-Scrapping imdb page for other information

In [52]:
import time
import random
import warnings
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

We will be using the normal distribution as the benchmark for the best movie recommender. Why? Skewed distribitions (either to the left or right) would indicate a bias in the rating behavior. Given enough data, the average movie should be closer to the number 3 from the scale of 1-5. Therefore, it will be something we look after when plotting.

We will be using Requests and Beautifulsoup for webscrapping. Our target is to gather information from multiple websites to evaluate which website is the most reliable to use for movie ratings

In [53]:
#scrolling to the next 50 movies (each page)
link = 'http://www.imdb.com/search/title?release_date=2017&sort=num_votes,desc&page=0'
response = requests.get(link)
print(response.text[0:500])

<!DOCTYPE html>
<html
    xmlns:og="http://ogp.me/ns#"
    xmlns:fb="http://www.facebook.com/2008/fbml">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="apple-itunes-app" content="app-id=342792525, app-argument=imdb:///?src=mdot">



        <script type="text/javascript">var IMDbTimer={starttime: new Date().getTime(),pt:'java'};</script>

<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadTitle"

If we head to the website and do inspection of the page, we'll see that all the movies are in the (div) (/div) tag, specifically, elements of each section of a movie is nested within (div class = "lister-item mode-advance"). There should be about 50 containers of these on each page.

We need to use BeautifulSoup to help parse the html. Documentation can be found on:
https://www.crummy.com/software/BeautifulSoup/bs4/doc/#beautifulsoup

In [54]:
html_soup = BeautifulSoup(response.text,"html.parser")
#type(html_soup)
#The find_all() method looks through a tagâ€™s descendants and retrieves all descendants that match your filters.
#Ie: looking through the "div" containers with class attribute of descendants being "lister-item mode-advanced"
total_containers = html_soup.find_all("div",class_="lister-item mode-advanced")
print(len(total_containers)) # a list of 50 containers

50

# Structures of the html page

%script false

The title is actually on the third (div), inside (h3), and further in (a). We don't use the (a) as an attribute because that there is also an earlier (a) from second (div) tag. We use (h3) to access the title. So in the end, we'll use "movie.h3.a" to access the title.

BeautifulSoup will search the entire page, but if a "tag" is repeated, it will "only" pick the first tag. In that case, try something under that tag that is unique.

##Year is under:
<h3 class="lister-item-header">
        <span class="lister-item-index unbold text-primary">4.</span>
    
    <a href="/title/tt2527336/?ref_=adv_li_tt">Star Wars: Episode VIII - Les derniers Jedi</a>
    <span class="lister-item-year text-muted unbold">(2017)</span>
</h3>
Therefore we access it with: h3 under class_ = "lister-item-year text-muted unbold"

##IMDB is under:
<div class="ratings-bar">
<div class="inline-block ratings-imdb-rating" name="ir" data-value="7,2">
        <span class="global-sprite rating-star imdb-rating"></span>
        <strong>7,2</strong>
    </div>
Therefore we can access it with: find("div",class_"ratings-bar").strong

##Metascore is under:
<div class="inline-block ratings-metascore">
<span class="metascore  favorable">85        </span>
        Metascore
            </div>
Therefore we can access it with: find("span",class_="metascore").text

##Vote is under:
<span name="nv" data-value="416246">416&nbsp;246</span>
Therefore we can access with: find("span", attrs={"name":"nv"})["data-value"])
Because we can search for any attributes under a dictionary form. Accessing the attribute without the comma will help us from converting the number.

##Gross is under:
<span name="nv" data-value="620&nbsp;181&nbsp;382">$620.18M</span>
This is just the same as Vote, but instead we can use fill_all("span", attrs={"name":"nv"})["data-value"]), and it will return in a list. The first element will be votes, and the second element will be Gross.

In [55]:
first_movie = total_containers[0]
#first_movie
first_title = first_movie.h3.a.text
first_title

first_year = first_movie.h3.find("span",class_="lister-item-year text-muted unbold").text
first_year = first_year[1:-1] #remove parenthesis
first_year

first_imdb = first_movie.find("div", class_="ratings-bar").strong
first_imdb.text

first_metascore = first_movie.find("span", class_="metascore").text 
#doesn't have to be the whole text "metascore favorable", not all scores are filled with that tag (errors)
first_metascore

first_vote = first_movie.find_all("span", attrs={"name":"nv"})[0]["data-value"]
first_vote

first_gross = first_movie.find_all("span",attrs={"name":"nv"})[1]["data-value"]
first_gross

'226,277,068'

In [56]:
#first page run-through
def web_scrap(total_containers):
    imdb_data = {"name":[],"year":[],"imdb":[],"metascore":[],"vote":[],"gross":[]}
    #since missing metascore and gross gave us errors, we'll only query items in which all rows are available.
    #this will also save us a lot of data clearning time later
    for movie in total_containers:
        if (movie.find('div', class_='ratings-metascore') is None) or ((len(movie.find_all("span", attrs={"name":"nv"})) < 2)):
            continue

        title = movie.h3.a.text
        imdb_data["name"].append(title)

        year = movie.h3.find("span",class_="lister-item-year text-muted unbold").text
        imdb_data["year"].append(year)

        imdb = movie.find("div", class_="ratings-bar").strong.text
        imdb_data["imdb"].append(float(imdb))

        metascore = movie.find("span", class_="metascore").text
        imdb_data["metascore"].append(int(metascore))

        vote = movie.find_all("span", attrs={"name":"nv"})[0]["data-value"]
        vote_ = vote.replace(",","") #parsing string "1,000" to 1000
        imdb_data["vote"].append(int(vote_))

        gross = movie.find_all("span", attrs={"name":"nv"})[1]["data-value"]
        gross_ = gross.replace(",","") #parsing string "1,000" to 1000
        imdb_data["gross"].append(int(gross_))
    return imdb_data

imdb_data = web_scrap(total_containers)
#imdb_data

In [57]:
#helper function to modify the year column
def year_mod(row):
    year = row.split("(")[-1] #will result in "2017)"
    return year[:-1]

#create a dataframe from the dictionary output of server request
def df_transform(imdb_data):
    temp_df = pd.DataFrame({'movie': imdb_data["name"],
                           'year': imdb_data["year"],
                           'imdb': imdb_data["imdb"],
                           'metascore': imdb_data["metascore"],
                           'votes': imdb_data["vote"],
                           'gross':imdb_data["gross"]})
    print(temp_df.info())
    return temp_df


temp_df = df_transform(imdb_data)
temp_year = temp_df["year"].apply(year_mod)
temp_df["year"] = temp_year
temp_df.head(5)
#webscrapping officially worked!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 6 columns):
gross        46 non-null int64
imdb         46 non-null float64
metascore    46 non-null int64
movie        46 non-null object
votes        46 non-null int64
year         46 non-null object
dtypes: float64(1), int64(3), object(2)
memory usage: 2.2+ KB
None

,gross,imdb,metascore,movie,votes,year
0,226277068,8.1,77,Logan,510160,2017
1,412563408,7.5,76,Wonder Woman,437645,2017
2,188373161,8.0,94,Dunkirk,419778,2017
3,620181382,7.2,85,Star Wars: Episode VIII - The Last Jedi,416461,2017
4,389813101,7.7,67,Guardians of the Galaxy Vol. 2,412289,2017

Now to iterate over many years and many pages, we have 2 controllers.

link = 'http://www.imdb.com/search/title?release_date=2017&sort=num_votes,desc&page=1'
where:
we need to change: 
1. release_data=2017
2. desc&page=1
3. Control the request rate, careful if we don't want to be classified as a ddos attack by the server!

# Putting it all together

In [58]:
def web_scrap_final(year_, pages_):
    years_req = [str(i) for i in range (year_,2019)] #scrapping all the way to the year 2018
    total_pages_req = [str(i) for i in range(0,pages_)] #6x50 = 300 per page if no missing data/errors

    start_time= time.time()
    total_requests = 0
    total_durations = 0
    imdb_total = {"name":[],"year":[],"imdb":[],"metascore":[],"vote":[],"gross":[]}
    for i in years_req:
        for j in total_pages_req:
            link = "http://www.imdb.com/search/title?release_date="+i+"&sort=num_votes,desc&page="+j
            response = requests.get(link)
            html_soup = BeautifulSoup(response.text,"html.parser")
            total_movies = html_soup.find_all('div', class_ = 'lister-item mode-advanced') #should be 50 items per page

            time.sleep(random.randint(1,4)) #crucial
            total_requests += 1
            total_duration = time.time() - start_time
            print("Request: ",total_requests, "Average sec per request: ", total_duration/total_requests)

            #good response = 200, we don't want to raise an exception, as some of the data will still be useful
            if response.status_code != 200:
                warn("Couldn't get a good response: error ",response.status_code)

            #consolidating dict, appending each pages into the end of the previous requests
            for key in imdb_total:
                imdb_total[key] += web_scrap(total_movies)[key]
    return imdb_total

imdb_total = web_scrap_final(2017,5)
df = df_transform(imdb_total)
temp_year = df["year"].apply(year_mod)
df["year"] = temp_year
df.to_csv("scrapped_test.csv")
df.head(10)

Request:  1 Average sec per request:  5.4967029094696045
Request:  2 Average sec per request:  5.474834561347961
Request:  3 Average sec per request:  5.761972983678182
Request:  4 Average sec per request:  5.598272740840912
Request:  5 Average sec per request:  5.124214220046997
Request:  6 Average sec per request:  5.098747690518697
Request:  7 Average sec per request:  5.236070428575788
Request:  8 Average sec per request:  5.215654730796814
Request:  9 Average sec per request:  5.194841437869602
Request:  10 Average sec per request:  5.169923710823059
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 6 columns):
gross        287 non-null int64
imdb         287 non-null float64
metascore    287 non-null int64
movie        287 non-null object
votes        287 non-null int64
year         287 non-null object
dtypes: float64(1), int64(3), object(2)
memory usage: 13.5+ KB
None

,gross,imdb,metascore,movie,votes,year
0,226277068,8.1,77,Logan,510160,2017
1,412563408,7.5,76,Wonder Woman,437645,2017
2,188373161,8.0,94,Dunkirk,419778,2017
3,620181382,7.2,85,Star Wars: Episode VIII - The Last Jedi,416461,2017
4,389813101,7.7,67,Guardians of the Galaxy Vol. 2,412289,2017
5,315058289,7.9,74,Thor: Ragnarok,388630,2017
6,334201140,7.5,73,Spider-Man: Homecoming,359216,2017
7,176040665,7.7,84,Get Out,333607,2017
8,92054159,8.1,81,Blade Runner 2049,332597,2017
9,107825862,7.6,86,Baby Driver,325563,2017

looks like we on average took out about 28 movies per page. Therefore, if we want about 2000 movies, it should be 10x of the current round. Obviously two solutions: increase the page, increase the year. We'll do a little of both

In [59]:
imdb_total = web_scrap_final(2005,15) #from 2005 until now, 15 pages per year.
df = df_transform(imdb_total)
temp_year = df["year"].apply(year_mod)
df["year"] = temp_year
df.to_csv("imdb_scrapped.csv")
df.head(10)

Request:  1 Average sec per request:  5.457341909408569
Request:  2 Average sec per request:  4.446001052856445
Request:  3 Average sec per request:  4.760790665944417
Request:  4 Average sec per request:  5.183119058609009
Request:  5 Average sec per request:  4.920573616027832
Request:  6 Average sec per request:  4.685903827349345
Request:  7 Average sec per request:  4.667958157403128
Request:  8 Average sec per request:  4.864551872014999
Request:  9 Average sec per request:  4.790406571494208
Request:  10 Average sec per request:  4.7264656066894535
Request:  11 Average sec per request:  4.6579622788862745
Request:  12 Average sec per request:  4.7119930783907575
Request:  13 Average sec per request:  4.736654318295992
Request:  14 Average sec per request:  4.841744644301278
Request:  15 Average sec per request:  4.736825593312582
Request:  16 Average sec per request:  4.67471744120121
Request:  17 Average sec per request:  4.777819829828599
Request:  18 Average sec per request:  4.821065558327569
Request:  19 Average sec per request:  4.91619536751195
Request:  20 Average sec per request:  4.898018956184387
Request:  21 Average sec per request:  4.92955157870338
Request:  22 Average sec per request:  4.953607775948265
Request:  23 Average sec per request:  5.01819778525311
Request:  24 Average sec per request:  5.08101545770963
Request:  25 Average sec per request:  5.086211795806885
Request:  26 Average sec per request:  5.016886032544649
Request:  27 Average sec per request:  4.989458110597399
Request:  28 Average sec per request:  4.932563858372824
Request:  29 Average sec per request:  4.971375103654532
Request:  30 Average sec per request:  4.910320369402568
Request:  31 Average sec per request:  4.90541329691487
Request:  32 Average sec per request:  4.851799882948399
Request:  33 Average sec per request:  4.872419183904475
Request:  34 Average sec per request:  4.830549324260039
Request:  35 Average sec per request:  4.8490225723811555
Request:  36 Average sec per request:  4.892588198184967
Request:  37 Average sec per request:  4.875240325927734
Request:  38 Average sec per request:  4.881109658040498
Request:  39 Average sec per request:  4.891367796139839
Request:  40 Average sec per request:  4.875021624565124
Request:  41 Average sec per request:  4.8836096379815075
Request:  42 Average sec per request:  4.872257283755711
Request:  43 Average sec per request:  4.885036629299785
Request:  44 Average sec per request:  4.910278412428769
Request:  45 Average sec per request:  4.944223626454671
Request:  46 Average sec per request:  4.93787656141364
Request:  47 Average sec per request:  4.9520268744610725
Request:  48 Average sec per request:  4.925515418251355
Request:  49 Average sec per request:  4.95963657632166
Request:  50 Average sec per request:  4.948756899833679
Request:  51 Average sec per request:  4.91897525506861
Request:  52 Average sec per request:  4.88348971421902
Request:  53 Average sec per request:  4.8508251343133315
Request:  54 Average sec per request:  4.875643610954285
Request:  55 Average sec per request:  4.895175925168124
Request:  56 Average sec per request:  4.89725826893534
Request:  57 Average sec per request:  4.865880911810356
Request:  58 Average sec per request:  4.854342172885763
Request:  59 Average sec per request:  4.856561612274687
Request:  60 Average sec per request:  4.862794383366903
Request:  61 Average sec per request:  4.844191328423922
Request:  62 Average sec per request:  4.859113693237305
Request:  63 Average sec per request:  4.893713269914899
Request:  64 Average sec per request:  4.8714019395411015
Request:  65 Average sec per request:  4.8823567573840805
Request:  66 Average sec per request:  4.889380498365923
Request:  67 Average sec per request:  4.880773565662441
Request:  68 Average sec per request:  4.886803293929381
Request:  69 Average sec per request:  4.860508929128232
Request:  70 Average sec per request:  4.854282900265285
Request:  71 Average sec per request:  4.847536439626989
Request:  72 Average sec per request:  4.84293673435847
Request:  73 Average sec per request:  4.8631222084777
Request:  74 Average sec per request:  4.839596297289874
Request:  75 Average sec per request:  4.856920359929402
Request:  76 Average sec per request:  4.87152077649769
Request:  77 Average sec per request:  4.896557377530383
Request:  78 Average sec per request:  4.890418514227256
Request:  79 Average sec per request:  4.900103747090207
Request:  80 Average sec per request:  4.894286724925041
Request:  81 Average sec per request:  4.912663642271065
Request:  82 Average sec per request:  4.928572500624308
Request:  83 Average sec per request:  4.943237856209996
Request:  84 Average sec per request:  4.935103107066381
Request:  85 Average sec per request:  4.94835472948411
Request:  86 Average sec per request:  4.943125139835269
Request:  87 Average sec per request:  4.945122529720438
Request:  88 Average sec per request:  4.92384714700959
Request:  89 Average sec per request:  4.912624629695764
Request:  90 Average sec per request:  4.890788102149964
Request:  91 Average sec per request:  4.898538041900802
Request:  92 Average sec per request:  4.881699608719868
Request:  93 Average sec per request:  4.867607611481861
Request:  94 Average sec per request:  4.8731924777335305
Request:  95 Average sec per request:  4.8800711581581515
Request:  96 Average sec per request:  4.885702311992645
Request:  97 Average sec per request:  4.889221525683846
Request:  98 Average sec per request:  4.8691083679393845
Request:  99 Average sec per request:  4.871986567372024
Request:  100 Average sec per request:  4.851565561294556
Request:  101 Average sec per request:  4.8338923171015065
Request:  102 Average sec per request:  4.8339997646855375
Request:  103 Average sec per request:  4.834028262536503
Request:  104 Average sec per request:  4.816536894211402
Request:  105 Average sec per request:  4.810447686059135
Request:  106 Average sec per request:  4.803023509259494
Request:  107 Average sec per request:  4.820716149339052
Request:  108 Average sec per request:  4.812328557173411
Request:  109 Average sec per request:  4.809659470111952
Request:  110 Average sec per request:  4.805752116983587
Request:  111 Average sec per request:  4.791416288496138
Request:  112 Average sec per request:  4.785021999052593
Request:  113 Average sec per request:  4.7892534163145895
Request:  114 Average sec per request:  4.774966254568937
Request:  115 Average sec per request:  4.769514915217524
Request:  116 Average sec per request:  4.754676775685672
Request:  117 Average sec per request:  4.740007899765276
Request:  118 Average sec per request:  4.725428916640201
Request:  119 Average sec per request:  4.720312000322743
Request:  120 Average sec per request:  4.722432484229405
Request:  121 Average sec per request:  4.716487413595531
Request:  122 Average sec per request:  4.714130540363124
Request:  123 Average sec per request:  4.720560936423821
Request:  124 Average sec per request:  4.711596444729836
Request:  125 Average sec per request:  4.701778360366822
Request:  126 Average sec per request:  4.697165627328176
Request:  127 Average sec per request:  4.695641252938218
Request:  128 Average sec per request:  4.692621806636453
Request:  129 Average sec per request:  4.695618829061819
Request:  130 Average sec per request:  4.700210961928734
Request:  131 Average sec per request:  4.713447319642278
Request:  132 Average sec per request:  4.7227339545885725
Request:  133 Average sec per request:  4.735614977384868
Request:  134 Average sec per request:  4.739522126183581
Request:  135 Average sec per request:  4.750301956247401
Request:  136 Average sec per request:  4.736700573388268
Request:  137 Average sec per request:  4.734081825200659
Request:  138 Average sec per request:  4.724428320276564
Request:  139 Average sec per request:  4.7310596404315755
Request:  140 Average sec per request:  4.727759058134897
Request:  141 Average sec per request:  4.725781354498356
Request:  142 Average sec per request:  4.727954599219308
Request:  143 Average sec per request:  4.7146373778790025
Request:  144 Average sec per request:  4.712657110558616

Request:  145 Average sec per request:  4.702341538462146
Request:  146 Average sec per request:  4.698559334833328
Request:  147 Average sec per request:  4.699916307618018
Request:  148 Average sec per request:  4.688404879054508
Request:  149 Average sec per request:  4.677290268392371
Request:  150 Average sec per request:  4.680028266906739
Request:  151 Average sec per request:  4.6681649748063245
Request:  152 Average sec per request:  4.66234795513906
Request:  153 Average sec per request:  4.673315805547378
Request:  154 Average sec per request:  4.68511332629563
Request:  155 Average sec per request:  4.698854406418339
Request:  156 Average sec per request:  4.690900781215766
Request:  157 Average sec per request:  4.695922777151606
Request:  158 Average sec per request:  4.698834177813953
Request:  159 Average sec per request:  4.693961666814936
Request:  160 Average sec per request:  4.690630862116814
Request:  161 Average sec per request:  4.698386149376816
Request:  162 Average sec per request:  4.6885828397892135
Request:  163 Average sec per request:  4.696516785884928
Request:  164 Average sec per request:  4.692923603988275
Request:  165 Average sec per request:  4.690009382999304
Request:  166 Average sec per request:  4.67875412716923
Request:  167 Average sec per request:  4.683671802817704
Request:  168 Average sec per request:  4.688597196624393
Request:  169 Average sec per request:  4.693084893141978
Request:  170 Average sec per request:  4.696603312211878
Request:  171 Average sec per request:  4.693862421470776
Request:  172 Average sec per request:  4.683823670065681
Request:  173 Average sec per request:  4.685741099319017
Request:  174 Average sec per request:  4.675589971158696
Request:  175 Average sec per request:  4.6765035602024625
Request:  176 Average sec per request:  4.677957187999379
Request:  177 Average sec per request:  4.68556666104807
Request:  178 Average sec per request:  4.6926410345548994
Request:  179 Average sec per request:  4.695662591710437
Request:  180 Average sec per request:  4.686414839161767
Request:  181 Average sec per request:  4.692310270024927
Request:  182 Average sec per request:  4.685665912680573
Request:  183 Average sec per request:  4.678987388402386
Request:  184 Average sec per request:  4.671212625244389
Request:  185 Average sec per request:  4.67782613006798
Request:  186 Average sec per request:  4.674246839297715
Request:  187 Average sec per request:  4.681945706433791
Request:  188 Average sec per request:  4.673685776426437
Request:  189 Average sec per request:  4.664511910191289
Request:  190 Average sec per request:  4.672035216030322
Request:  191 Average sec per request:  4.663531382046445
Request:  192 Average sec per request:  4.664608256270488
Request:  193 Average sec per request:  4.66076860032551
Request:  194 Average sec per request:  4.657161551652496
Request:  195 Average sec per request:  4.657550815435556
Request:  196 Average sec per request:  4.658722596509116
Request:  197 Average sec per request:  4.665849523495901
Request:  198 Average sec per request:  4.668694030154835
Request:  199 Average sec per request:  4.661143507789727
Request:  200 Average sec per request:  4.661956804990768
Request:  201 Average sec per request:  4.6526604778137965
Request:  202 Average sec per request:  4.659029342160366
Request:  203 Average sec per request:  4.649162059934269
Request:  204 Average sec per request:  4.64281325597389
Request:  205 Average sec per request:  4.634774292969122
Request:  206 Average sec per request:  4.640744238223844
Request:  207 Average sec per request:  4.6386783491586145
Request:  208 Average sec per request:  4.629465351884182
Request:  209 Average sec per request:  4.62057900428772
Request:  210 Average sec per request:  4.617633275758653
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4546 entries, 0 to 4545
Data columns (total 6 columns):
gross        4546 non-null int64
imdb         4546 non-null float64
metascore    4546 non-null int64
movie        4546 non-null object
votes        4546 non-null int64
year         4546 non-null object
dtypes: float64(1), int64(3), object(2)
memory usage: 213.2+ KB
None

,gross,imdb,metascore,movie,votes,year
0,206852432,8.3,70,Batman Begins,1145123,2005
1,70511035,8.2,62,V for Vendetta,919884,2005
2,74103820,8.0,74,Sin City,704534,2005
3,380262555,7.6,68,Star Wars: Episode III - Revenge of the Sith,614004,2005
4,290013036,7.7,81,Harry Potter and the Goblet of Fire,460844,2005
5,186336279,6.5,55,Mr. & Mrs. Smith,400277,2005
6,234280354,6.5,73,War of the Worlds,375174,2005
7,206459076,6.7,72,Charlie and the Chocolate Factory,372191,2005
8,218080025,7.2,81,King Kong,355427,2005
9,109449237,7.1,73,The 40-Year-Old Virgin,350530,2005

Voila! Now we're transporting these data back to the orginal analysis