In [4]:
from keras.datasets import imdb
import numpy as np

In [2]:
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(
    num_words=10000)

Downloading data from https://s3.amazonaws.com/text-datasets/imdb.npz
17285120/17464789 [============================>.] - ETA: 0s

In [9]:
np.max(train_data)

[1,
 9995,
 2,
 7,
 2208,
 7335,
 3135,
 4173,
 3783,
 509,
 1683,
 4702,
 2,
 2,
 6,
 201,
 7,
 6415,
 687,
 2,
 2,
 7,
 6387,
 548,
 139,
 7583,
 295,
 34,
 4485,
 5302,
 2,
 2,
 2,
 7,
 2,
 2,
 146,
 24,
 1017,
 2282,
 133,
 21,
 4,
 1591,
 3113,
 786,
 2,
 16,
 125,
 4,
 2,
 9790,
 2039,
 137,
 267,
 2,
 5,
 2,
 120,
 2024,
 980,
 2,
 1248,
 5666,
 727,
 1405,
 6879,
 1060,
 6442,
 18,
 2,
 1461,
 2,
 1883,
 445,
 109,
 5369,
 3696,
 33,
 236,
 786,
 5580,
 7994,
 8,
 2,
 2,
 103,
 2,
 98,
 11,
 2,
 1461,
 24,
 66,
 351,
 1461,
 165,
 116,
 17,
 2545,
 18,
 6717,
 8694,
 5514,
 980,
 2545,
 165,
 734,
 18,
 2311,
 52,
 84,
 157,
 18,
 7232,
 11,
 661,
 8,
 607,
 3531,
 223,
 1066,
 445,
 9236,
 996,
 8,
 2898,
 4931,
 8,
 5526,
 8316,
 7880,
 154,
 378,
 459,
 18,
 6942,
 632,
 5,
 79,
 2024,
 18,
 68,
 4918,
 813,
 2456,
 2,
 17,
 840,
 4807,
 3854,
 23,
 136,
 159,
 5770,
 852,
 1698,
 632,
 7708,
 7993,
 1003,
 1372,
 5747,
 2,
 7,
 5840,
 5408,
 11,
 7200,
 120,
 4682,
 7,
 2,
 3368,
 2103,
 8,
 1140,
 2,
 880,
 1692,
 7,
 68,
 205,
 3565,
 5903,
 21,
 3204,
 1372,
 2,
 2,
 1098,
 125,
 128,
 2429,
 21,
 9000,
 2,
 632,
 2,
 245,
 39,
 3526,
 5,
 9386,
 2690,
 6,
 4951,
 7,
 2,
 496,
 90,
 103,
 316,
 47,
 348,
 56,
 2,
 483,
 2,
 2865,
 56,
 6,
 9739,
 445,
 9236,
 2568,
 2464,
 8,
 632,
 29,
 57,
 1207,
 1085,
 17,
 6,
 3842,
 632,
 3055,
 8,
 516,
 5765,
 2,
 88,
 240,
 128,
 74,
 15,
 7906,
 700,
 2143,
 109,
 166,
 642,
 2,
 5,
 6358,
 795,
 7771,
 6474,
 2,
 11,
 1526,
 4041,
 2,
 2,
 2,
 2,
 2,
 31,
 160,
 143,
 6,
 201,
 7,
 3404,
 5,
 85,
 1748,
 2,
 15,
 62,
 516,
 6,
 2691,
 6945,
 132,
 2,
 4193,
 7,
 1056,
 6756,
 4262,
 19,
 164,
 21,
 2,
 2,
 1141,
 281,
 5,
 4,
 4461,
 7,
 5681,
 2,
 5,
 1175,
 2,
 2628,
 7232,
 772,
 447,
 2066,
 588,
 17,
 8508,
 18,
 5580,
 2,
 10,
 10,
 13,
 100,
 140,
 23,
 21,
 14,
 9,
 43,
 2,
 48,
 335,
 120,
 4,
 559,
 7,
 3917,
 5,
 24,
 581,
 11,
 9484,
 3231,
 225,
 242,
 164,
 133,
 18,
 25,
 2,
 195,
 45,
 24,
 99,
 230,
 125,
 7,
 2291,
 18,
 3783,
 102,
 38,
 2,
 32,
 207,
 398,
 48,
 25,
 191,
 79,
 195,
 7,
 4,
 512]

In [13]:
print(np.size(train_data[0]))
print(np.size(train_data))
#what does this mean? 218 words review for the first output. 25k reviews total in the second output.
#each word is mapped to an integer, up to 10000 unique words (based on usage).

218
25000

In [15]:
print(np.size(train_data[2]))

141

In [16]:
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results

In [17]:
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

In [19]:
np.max(x_train)

1.0